### ISSUE TITLE
Workflow - Outline metadata and identify gaps in current schema by documenting the current workflows

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/workflow_documentation#2]
Shane, Paul and Bin and team will document current workflows and link to their documentation in this issue.  This information will be used by Yuri for the design document.

**Comment by ssarrafan** [comment]
Paul P didn't have access to org so I've invited him and will add to this issue once he accepts.

**Comment by ssarrafan** [comment]
Documentation link from Shane: https://drive.google.com/drive/u/0/folders/1lcxLv6rgxQZ1ujnhx27LLx_iapMZ13RQ

**Comment by hubin-keio** [comment]
Metagenome assembled genomes generation workflow documentation from Mark and Yuri: https://docs.google.com/document/d/1ccrO-VdeObcrCi4bbJkUP9QxErz-PDyNqbL_0KiOvBI

**Comment by hubin-keio** [comment]
Metabolomics workflow from Yuri: https://docs.google.com/document/d/15hvd_G9wMxIOphUCQsVIQI-C2GrLYnMMTfFR258gzR0

**Comment by ssarrafan** [comment]
@hubin-keio can this issue be closed based on your comments? Or is there more that needs to be done to consider this complete?

**Comment by ssarrafan** [comment]
Discussed this with KJ and we are closing this one.
