### ISSUE TITLE
Workflow - Draft design document based on workflow documentation

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/workflow_documentation#3]
Yuri will work on this draft based on the current workflow documentation provided by Shane, Paul, Bin and team.  See https://github.com/microbiomedata/workflow_documentation/issues/2

**Comment by corilo** [comment]
working draft here: https://miro.com/app/board/o9J_lXwjL98=/
and workflows documents here: https://drive.google.com/drive/u/0/folders/1lcxLv6rgxQZ1ujnhx27LLx_iapMZ13RQ

**Comment by corilo** [comment]
closing the issue, the draft is complete, and a new issue has been created to track the status here::
https://github.com/microbiomedata/workflow_documentation/issues/5#event-4658177596
