### ISSUE TITLE
Workflow - Draft data management plan based on design document

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/workflow_documentation#4]
Donny will work on drafting a data management plan based on Yuri's design document and other documentation provided by the team. Related to https://github.com/microbiomedata/workflow_documentation/issues/3

**Comment by dwinston** [comment]
meeting scheduled with @corilo this Monday (2021-04-12) afternoon.

**Comment by dwinston** [comment]
Met with @scanon and @corilo today. Good progress via "NMDC Planning" Miro board.

Next step is me preparing sequence diagrams (and an API glossary sufficient to clarify the messages in these diagrams) for our next meeting, scheduled for Tuesday (2021-04-20).

**Comment by dwinston** [comment]
more progress documented on the Miro board. My sequence diagram is also [here](https://github.com/microbiomedata/nmdc-runtime/blob/1beb157b6c655a11db255e99f0fa27015464b06e/docs/design/workflow-automation.md). Next step is to revise the diagram as per feedback, and to draft a document motivating and describing the plan and intended API. We are scheduled to meet again on 2021-04-27.

**Comment by dwinston** [comment]
I have completed an initial draft of the NMDC Runtime API as FastAPI stubs that produce an OpenAPI spec. The resource layout currently covers aspects of workflow execution and automation, and is intended to facilitate discussion as more of the API is developed. The api code is in microbiomedata/nmdc-runtime [here](https://github.com/microbiomedata/nmdc-runtime/tree/214ad97c697dd748543282954a7615510fb10e46/nmdc_runtime/api).

The link to rendered API documentation under the microbiomedata.github.io domain will be available and provided once I can enable github pages on the repo. @dehays is helping me with this.

The follow-up issue to track for the next sprint is #5.
