### ISSUE TITLE
complete design doc / api spec for automation

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/workflow_documentation#5]
- [x] design doc
- [x] api spec
- [x] demo automation at two execution sites

**Comment by dwinston** [comment]
Once done, a follow-up issue would be "demo automation at an execution site"

**Comment by dwinston** [comment]
@corilo @scanon based on recent discussion at the tech sync, the follow-up issue would be "demo automation at two execution sites"

**Comment by dwinston** [comment]
@ssarrafan this repo needs t-shirt labels. :)

**Comment by dwinston** [comment]
draft API docs: <https://microbiomedata.github.io/nmdc-runtime/design/redoc-static.html>

**Comment by ssarrafan** [comment]
T-shirt size labels have been created for the workflow-documentation repo

**Comment by ssarrafan** [comment]
@scanon @dwinston @hubin-keio @corilo can this issue be closed?  Does it need to continue into the next sprint?

**Comment by dwinston** [comment]
We have a design doc and api spec up at <https://microbiomedata.github.io/nmdc-runtime/>, but I think we still need the demo component to be sure our design makes sense. So this issue should remain open.

**Comment by ssarrafan** [comment]
@dwinston thank you for documenting updates in this GH issue.  I'm going to remove the other assignees so we can have issues assigned to one person at a time. If it needs to be transferred to someone else let me know or add them and remove yourself as an assignee.  Thanks!

**Comment by dwinston** [comment]
Shared a design doc and api spec with the team via google drive ("Automation Notes" folder). I think what remains is to demo execution to prove to ourselves that the design is workable.

**Comment by ssarrafan** [comment]
@dwinston I'll move to July sprint for the remaining demo but let me know if it should be assigned to someone else now.

**Comment by ssarrafan** [comment]
@dwinston can this issue be closed?  Was the demo done?

**Comment by hubin-keio** [comment]
Can we move the issue to the run-time API repo? This repo is for workflow documentation only. Thanks!

**Comment by dwinston** [comment]
Has been demonstrated for NERSC and for the nmdc-runtime site on NERSC Spin for metadata validation/ingest.
